"""empty message

Revision ID: 93faa3e81791
Revises: eff0ff927d90
Create Date: 2022-11-23 22:47:43.097003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93faa3e81791'
down_revision = 'eff0ff927d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    # ### end Alembic commands ###
